CREATE TABLE `trial` (
 `trial_seq` int(11) NOT NULL AUTO_INCREMENT,
 `trial_name` varchar(100) NOT NULL,
 `start_dt` datetime NOT NULL,
 `end_dt` datetime NOT NULL,
 `user` varchar(15) NOT NULL,
 `proc_chg_num` varchar(15) DEFAULT NULL,
 `twi_num` varchar(15) DEFAULT NULL,
 `unit` text,
 `trial_type` varchar(20) DEFAULT NULL,
 `change_type` varchar(20) DEFAULT NULL,
 `bop_vsl` tinyint(4) DEFAULT NULL,
 `degas_vsl` tinyint(4) DEFAULT NULL,
 `argon_station` tinyint(4) DEFAULT NULL,
 `caster_num` tinyint(4) DEFAULT NULL,
 `strand_num` tinyint(4) DEFAULT NULL,
 `comment_goal` text,
 `comment_monitor` text,
 `comment_general` text,
 `comment_conclusion` text,
 `create_dt` datetime DEFAULT NULL,
 `update_dt` datetime DEFAULT NULL,
 PRIMARY KEY (`trial_seq`)
) ENGINE=InnoDB AUTO_INCREMENT=106 DEFAULT CHARSET=latin1